--BÝR MAÐAZANIN GÜN BAZLI SATIÞLARI--
SELECT *
FROM SALES WHERE CITY='ANKARA'
ORDER BY DATE_
UPDATE SALES SET DATE2=CONVERT(DATE,DATE_)
----------------------------------------------------------------------
SELECT * FROM SALES WHERE CITY='ANKARA' ORDER BY DATE2
----------------------------------------------------------------------
SELECT CITY,DATE2,SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES WHERE CITY='ANKARA'
GROUP BY CITY,DATE2 --> YUKARIDA AGGREGATE FONSIYON KULLANDIÐIM ÝÇÝN AÞAÐIDA GROUPBY YAPMAZSAM HATA ALIRIM!
ORDER BY CITY,DATE2
----------------------------------------------------------------------
--BÝR GÜNÜN MAÐAZA BAZLI SATIÞLARI--
SELECT DATE2,CITY,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES
WHERE DATE2='20190101'
GROUP BY DATE2,CITY
ORDER BY DATE2,SUM(TOTALPRICE) DESC -->TOPLAM FÝYATA VE ÞEHÝRE GÖRE SIRALA
----------------------------------------------------------------------
--MAÐAZALARIN AYLARA GÖRE SATIÞ RAKAMLARINI GETÝRME--
SELECT * FROM SALES

UPDATE SALES SET MONTHNAME_='01.OCAK' WHERE DATEPART(MONTH,DATE2)=1 --> 01.OCAK YAZMAMIN SEBEBÝ BURASI BÝR METÝN ÝFADESÝ VE SIRALAMA DA ARALIK OCAKTAN ÖNCE GELMESÝN KARIÞIKLIK YAÞANMAMASI ÝÇÝN ÖNCELÝKLE BUNU YAZDIM!
UPDATE SALES SET MONTHNAME_='02.ÞUBAT' WHERE DATEPART(MONTH,DATE2)=2
UPDATE SALES SET MONTHNAME_='03.MART' WHERE DATEPART(MONTH,DATE2)=3
UPDATE SALES SET MONTHNAME_='04.NÝSAN' WHERE DATEPART(MONTH,DATE2)=4
UPDATE SALES SET MONTHNAME_='05.MAYIS' WHERE DATEPART(MONTH,DATE2)=5
UPDATE SALES SET MONTHNAME_='06.HAZÝRAN' WHERE DATEPART(MONTH,DATE2)=6
UPDATE SALES SET MONTHNAME_='07.TEMMUZ' WHERE DATEPART(MONTH,DATE2)=7
UPDATE SALES SET MONTHNAME_='08.AÐUSTOS' WHERE DATEPART(MONTH,DATE2)=8
UPDATE SALES SET MONTHNAME_='09.EYLÜL' WHERE DATEPART(MONTH,DATE2)=9
UPDATE SALES SET MONTHNAME_='10.EKÝM' WHERE DATEPART(MONTH,DATE2)=10
UPDATE SALES SET MONTHNAME_='11.KASIM' WHERE DATEPART(MONTH,DATE2)=11
UPDATE SALES SET MONTHNAME_='12.ARALIK' WHERE DATEPART(MONTH,DATE2)=12
----------------------------------------------------------------------
SELECT CITY,MONTHNAME_ , SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
GROUP BY CITY,MONTHNAME_ --> ÞEHÝRLERÝN AYLARA GÖRE SATIÞLARI
ORDER BY CITY,MONTHNAME_
----------------------------------------------------------------------
SELECT CITY,MONTHNAME_ , SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
GROUP BY MONTHNAME_ , CITY -->AYLARIN ÞEHÝRLERE GÖRE SATIÞLARI
ORDER BY MONTHNAME_ ,CITY 
----------------------------------------------------------------------
SELECT CITY,MONTHNAME_ , SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
GROUP BY CITY,MONTHNAME_  -->ÞEHÝRLERÝN AYLARA GÖRE SATIÞLARI
ORDER BY CITY,MONTHNAME_ 
----------------------------------------------------------------------
SELECT MONTHNAME_ ,CITY, SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
GROUP BY CITY,MONTHNAME_ 
ORDER BY MONTHNAME_ ,SUM(TOTALPRICE) DESC -->AYA GÖRE ÞEHÝRLERÝN TOPLAM SATIÞLARI
----------------------------------------------------------------------
--ÜRÜN KATEGORÝLERÝNE GÖRE SATIÞ RAKAMLARINI GETÝRME--
SELECT CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4,
SUM(TOTALPRICE) AS TOTALPRICE, --> FÝYAT OLARAK NE KADAR
COUNT(*) AS ROWCOUNT_,
SUM(AMOUNT) AS TOTALAMOUNT -->ADET OLARAK NE KADAR
FROM SALES
GROUP BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4
ORDER BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4
-->150000 SATIRLIK VERÝYÝ KATEGORYLEYEREK 786 SATIRA DÜÞÜRDÜM!
----------------------------------------------------------------------
--MAÐAZALARIN MÜÞTERÝ SAYILARINI GETÝRME--
SELECT * FROM SALES WHERE MONTHNAME_='01.OCAK' AND CITY='ADANA' --> 386 SONUÇ GELDÝ FAKAT AYNI FÝÞTEKÝ BÝLGÝLER DE VAR BUNU AYIRT ETMEK ÝÇÝN GROUP BY YAPICAM!
----------------------------------------------------------------------
SELECT FICHENO,COUNT(*)
FROM SALES WHERE MONTHNAME_='01.OCAK' AND CITY='ADANA'
GROUP BY FICHENO
-----------------------------------------------------------------------
SELECT CITY,COUNT(DISTINCT CUSTOMERNAME) AS UNIQUECUSTOMER, -->AYNI KÝÞÝYE KESÝLMEYEN FATURALAR ÝÇÝN!
COUNT(DISTINCT FICHENO) AS CUSTOMERCOUNT, -->FÝÞ NUMARALARI AYNI OLMAYANLARI ÞEHÝRLERE GÖRE GRUPLAYIP, SIRALADIM!
COUNT(*) AS ITEMCOUNT -->OKUTULAN BARKOD
FROM SALES WHERE MONTHNAME_='01.OCAK'
GROUP BY CITY
ORDER BY CITY
-----------------------------------------------------------------------
--BELÝRLÝ BÝR CÝRO ÜZERÝNDE SATIÞ YAPAN MAÐAZALARI GETÝRME--
SELECT CITY,SUM(TOTALPRICE)AS TOTALPRICE,
COUNT(DISTINCT CUSTOMERNAME) AS CUSTOMERCOUNT
FROM SALES
--WHERE TOTALPRICE>40000 --> 0 SATIR GETÝRÝR ÇÜNKÜ SATIRLARA TEK TEK BAKIYOR TOPLAM 40000 OLARAK ALGILAMIYOR! (BUNUN ÝÇÝN HAVING KULLAN)
GROUP BY CITY 
HAVING SUM(TOTALPRICE)>40000 -->TOPLAM CIROSU 40000 ÝN ÜZERÝNDE OLAN, ÞEHÝRLERÝ GRUPLAYIP, CÝROYA GÖRE SIRALAYIP GETÝRÝR!
--HAVING COUNT(DISTINCT CUSTOMERNAME)>1000 -->1000DEN FAZLA TEKÝL MÜÞTERÝSÝ OLANI GETÝRÝR!
ORDER BY SUM(TOTALPRICE) DESC
------------------------------------------------------------------------
