
CREATE VIEW VW_TOP10_KATEGORI -->VIEW IN ICINE VIEW AÇMIÞ OLDUM!
AS
SELECT TOP 10 KATEGORI1,SUM(SATIRTOPLAMI) AS TOPLAMTUTAR
FROM VW_SIPARIS_DETAYI
GROUP BY KATEGORI1
ORDER BY SUM(SATIRTOPLAMI) DESC

SELECT * FROM VW_TOP10_KATEGORI