SET STATISTICS IO ON
SELECT * FROM CUSTOMERS WHERE NAMESURNAME LIKE 'ÖMER ÇOLAKOÐLU' 

--> TABLE SCAN: EN KÖTÜ EN VERÝMSÝZ ARAMA ÞEKLÝDÝR! (TABLODA PRIMARY KEY YOKSA BOYLE YAPAR!)
--> CLUSTERED INDEX SCAN: PAGELERÝ SIRAYA SOKAR AMA ÝSME GÖRE BÝR SIRALAMA YOK!

SP_SPACEUSED 'CUSTOMERS' -->TEK BÝR TABLONUN BOYUTUNA BAKMAK ÝSTERSEM!

SET STATISTICS IO ON

SELECT * 
FROM CUSTOMERS 
WHERE NAMESURNAME = 'ÖMER ÇOLAKOÐLU'

-->INDEX SEEK: BINARY TREE YE GÖRE ÝKÝYE BÖLEREK ARAMASI!

-->KEY LOOKUP: ÖNCE ID YÝ BULDUM SONRA SELECT * FROM CUSTOMERS WHERE ID=168483 Ü GETÝRDÝM DÝYOR! (2 ÝÞLEM YAPTI)

SET STATISTICS IO ON
SELECT NAMESURNAME 
FROM CUSTOMERS 
WHERE NAMESURNAME = 'ÖMER ÇOLAKOÐLU' --> ÝÇERÝSÝNDE AD SOYAD BÝLGÝSÝ MEVCUT OLDUÐU ÝÇÝN BAÞKA BÝR YERE BAKMADI! NONCLUSTERED INDEX ÝLE ÝÞÝ HALLETTÝ! (KEY LOOKUP YAPMAZ!)

--INCLUDED COLUMN -->INDEX LÝ BÝR ALANIM VAR AMA DÝÐER ALANLARI DA KENDÝ ÝÇERÝSÝNDE ÝÇERÝYOR(INCLUDE EDÝYOR)! 

SP_SPACEUSED 'CUSTOMERS'           
1007560 KB -->REVERSED
429712 KB -->DATA
578728 KB -->INDEX_SIZE
0 KB -->UNUSED

SET STATISTICS IO ON --> KAÇ PAGE OKUDUÐUMA BAKIYORUM !
SELECT * FROM CUSTOMERS --> SADECE TELEFON ÝÇÝN INDEX OLUÞTURDUM VE ÇOK DAHA HIZLI GELDÝ!
WHERE TELNR='03423344747'
--> INDEX OLUNCA 6 PAGE OKURKEN INDEX OLMAYINCA 31000 PAGE OKUYOR !
AND NAMESURNAME='ÖMER ÇOLAKOÐLU' --> NAMESURNAME VE TELNR NIN FARKLI YERLERDE OLMASI SONUCUMU ETKÝLEMEZ'

SELECT * FROM CUSTOMERS
WHERE BIRTHDATE='1964-03-30'

SELECT * FROM CUSTOMERS
WHERE TCNO='54982792910'

-------------------------------------------UNIQUE INDEX--------------------------------------------------

SELECT * FROM CUSTOMERS WHERE NAMESURNAME='ÖMER ÇOLAKOÐLU'

--> ÖMER ÇOLAKOÐLUNDAN 1 TANE OLDUÐUNU SQL SERVER A SÖYLERSEM DÝÐER DATALARA BOÞ YERE BAKMAYACAK!
--> ID, TCNO DEÐRLERÝ UNIQUE DIR TEKRAR ETMEZ BUNU INDEX'IN PROPERTIES IN DEN UNIQUE ÝÞARETLEYEBÝLÝRSÝN!

SELECT * FROM CUSTOMERS WHERE TCNO='54982792910'

SELECT * FROM CUSTOMERS WHERE ID=35578
WHERE TCNO='10019865823'

UPDATE CUSTOMERS SET TCNO='54982792910' WHERE ID=35578 --> TCNO UNIQUE OLDUÐU ÝÇÝN BU ÝÞLEME ÝZÝN VERMEZ!!!!

--DUPLICATE:TEKRAR EDEN VERÝ

----------------------------------------INDEX BOZULMALARI------------------------------------------------

-->BURADA YAPTIÐIMIZ ÖRNEKLER STATIC VERÝLER AMA GERÇEK HAYATTA DÝNAMÝK BÝR YAPI OLACAK VE SÜREKLÝ DB GÜNCELLENECEK
--BU DA INDEX BOZULMALARINA SEBEBIYET VERMEKTEDÝR!

--GERÇEKTE OLAN YENÝ GELEN VERÝLER DÝÐERLERÝNÝ BOZMAMASI ADINA FARKLI BÝ PAGE IN ÝÇÝNE GÝRER BUNLAR SIRASIZ(INDEX BOZUK) BÝR ÞEKÝLDEDÝR!

-->FRAGMANTATION: INDEXLERIN BOZULMASI!! 

-->BUNLAR BELLÝ ARALIKLARLA DÜZELTÝLÝR BUNA DA 'REBUILD' ADI VERÝLÝR! (DATABASE BAKIM PLANLARINDAN BÝRÝ)

-->INDEX DÜZENLEME MALÝYETLÝ BÝR ÝÞLEMDÝR! SÝSTEM KAPALIYKEN YAPILMASI TAVSÝYE EDÝLÝR!

-->PAGELERÝN ÝÇÝNDE BOÞLUK BIRAKARSAK '(FILL FACTOR(DOLULUK ORANI))' YENÝ GELEN DATA KOSKOCA VERÝTABANINDA DEÐÝL SADECE ÝLGÝLÝ PAGE DE KAYMAYA BÝR SEBEBÝYET VERÝR, BUNU DÜZELTMESÝ DAHA AZ MALÝYETLÝ OLUR!

---------------------------------------------------------------------------------------------------------

-->INDEXLERIN BOZULMASI ARAMA HIZINA DOÐRUDAN YANSIR!

-->FRAGMANTATION BOZULDUKTAN SONRA REBUILD YAPARSAN TEKRAR %0.04 GÝBÝ SEVÝYELERE DÜÞER!

-->REORGANIZE REBUILDE GÖRE NISPETEN DAHA UZUN SÜRER O DA FRAGMANTATION DEÐERÝNÝ DÜÞÜRÜR! -->INDEX BOZULMALARINI DÜZELTME YÖNTEMÝ

--REBUILD HER ÞEYÝ SÝLBAÞTAN YAPAR, REORGANIZE KENDÝ ÝÇERÝSÝNDE TEKRAR SIRALAR!

-->FRAGMANTATION %40'IN ALTINDAYSA REORGANIZE KULLANABÝLÝRSÝN!

-->FRAGMANTATION %40'IN ÜSTÜNDEYSE REBUILD TAVSÝYE EDÝLÝR! (ÝÞÝNÝ GARANTÝYE ALMAK ÝSTÝYORSAN BUNU KULLAN!)


-----------------------------------ÝSTATÝSTÝKLER--------------------------------------------------------

SELECT * FROM CUSTOMERS WITH(INDEX=IXBIRTHDATE) --> BURADA INDEX OLARAK IXBIRTHDATE I KULLANMAYA ZORLADIM! (ÇOK DOÐRU BÝR HAREKET DEÐÝL!)
WHERE BIRTHDATE='1996-03-09' -->DAHA AZ MALÝYETLÝ OLANA GÖRE ARAMA YAPIYOR!
AND NAMESURNAME='ADA SÖZÜER'

SELECT COUNT(*) FROM CUSTOMERS WHERE BIRTHDATE='1996-03-09'
SELECT COUNT(*) FROM CUSTOMERS WHERE NAMESURNAME='ADA SÖZÜER'

WHERE NAMESURNAME='ADA SÖZÜER'

--> HER INDEX IN ALTINDA BÝR ÝSTATÝSTÝK DEÐERÝ TUTULUR!

-->REORGANIZE VE REBUILD ETMEK ÝSTATÝKTÝKLERÝ OTOMATÝK OLARAK GÜNCELLER!

SP_UPDATESTATS --> BU VERÝ TABANIMDAKÝ TÜM TABLOLARIN ÝSTATÝSTÝKLERÝNÝ GÜNCELLER!

UPDATE STATISTICS CUSTOMERS --> CUSTOMER TABLOSUNUN ÝSTATÝSTÝKLERÝNÝ GÜNCELLER!

---------------------------------------------------------------------------------------------------------






