SELECT * FROM USERS

SELECT * FROM ADDRESS
--------------------------------------------
SELECT  --INNER JOIN--
U.ID,U.ID,A.ADDRESSTEXT
FROM USERS U JOIN ADDRESS A ON A.USERID=U.ID
--------------------------------------------
SELECT  --LEFT JOIN--
U.ID,U.ID,A.ADDRESSTEXT
FROM USERS U LEFT JOIN ADDRESS A ON A.USERID=U.ID
--LEFT JOIN ÝFADESÝNÝN SOLUNDA KALAN SOL TABLO SAÐINDA KALAN SAÐ TABLODUR!
--------------------------------------------
SELECT  --RIGHT JOIN--
U.ID,U.ID,A.ADDRESSTEXT
FROM USERS U RIGHT JOIN ADDRESS A ON A.USERID=U.ID
--------------------------------------------
SELECT  --FULL JOIN--
U.ID,U.ID,A.ADDRESSTEXT
FROM USERS U FULL JOIN ADDRESS A ON A.USERID=U.ID