--TARÝHE GÖRE SÝPARÝÞ DAÐILIMINI GETÝREN SORGU--
SELECT
--CONVERT(DATE,O.DATE_) TARIH, -->TARIH-SAAT BÝLGÝSÝNÝ TARÝHE CEVÝRDÝM!
DATEPART(YEAR,O.DATE_) AS YIL,
DATEPART(MONTH,O.DATE_) AS AY, -->DATEPART TARÝHÝN ÝÇERÝSÝNDEN SADECE AY DEÐERÝNÝ GETÝRÝR!
CASE 
	WHEN DATEPART(MONTH,O.DATE_)=1 THEN 'OCAK' -->1.AYA OCAK DEDÝM
	WHEN DATEPART(MONTH,O.DATE_)=2 THEN 'ÞUBAT' -->2.AYA ÞUBAT DEDÝM
	WHEN DATEPART(MONTH,O.DATE_)=3 THEN 'MART'
	WHEN DATEPART(MONTH,O.DATE_)=4 THEN 'NÝSAN'
	WHEN DATEPART(MONTH,O.DATE_)=5 THEN 'MAYIS'
	WHEN DATEPART(MONTH,O.DATE_)=6 THEN 'HAZÝRAN'
	WHEN DATEPART(MONTH,O.DATE_)=7 THEN 'TEMMUZ'
	WHEN DATEPART(MONTH,O.DATE_)=8 THEN 'AÐUSTOS'
	WHEN DATEPART(MONTH,O.DATE_)=9 THEN 'EYLÜL'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'EKÝM'
	WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'KASIM'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'ARALIK'
END AS AYADI,
SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTAR,
SUM(OD.AMOUNT) AS TOPLAMSIPARIS_MIKTAR,
COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI
FROM ORDERS O
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
GROUP BY DATEPART(YEAR,O.DATE_),DATEPART(MONTH,O.DATE_)
ORDER BY DATEPART(YEAR,O.DATE_) ,DATEPART(MONTH,O.DATE_)
-------------------------------------------------------------------------------
--ÖDEME TÜRÜNE GÖRE DAÐILIM--
SELECT 
DATEPART(MONTH,DATE_) AS AY, DATEPART(YEAR,DATE_) AS YIL,
CASE
	WHEN PAYMENTTYPE=1 THEN 'KREDÝ KARTI'
	WHEN PAYMENTTYPE=2 THEN 'BANKA HAVALESÝ'
END AS ODEMETURU_ACIKLAMA,
SUM(PAYMENTTOTAL) AS TOPLAMTUTAR
FROM PAYMENTS
GROUP BY DATEPART(MONTH,DATE_),PAYMENTTYPE, DATEPART(YEAR,DATE_) -->PAYMENTTYPE AGGREGATE FUNCTION ÝÇERDÝÐÝ ÝÇÝN GROUP BY'A KOYMAK ZORUNDASIN!
ORDER BY DATEPART(MONTH,DATE_), DATEPART(YEAR,DATE_)
-------------------------------------------------------------------------------
--ORTALAMA TESLÝMAT SÜRESÝ--(ÞÝRÝÞ TARÝHÝ ÝLE FATURA TARÝHÝ ARASINDAKÝ FARK)--
SELECT
O.ID AS SIPARISID,
O.DATE_ AS SIPARISTARIHI,
I.DATE_ AS FATURATARIHI,
DATEDIFF(HOUR,O.DATE_,I.DATE_) AS TESLIMATSURESI_SAAT
--AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ORTALAMA_TESLIMATSURESI_SAAT -->ORTALAMA TESLÝMAT SÜRESÝ
--MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ENKISA_TESLIMATSURESI_SAAT -->EN KISA TESLÝMAT SÜRESÝ
--MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ENUZUN_TESLIMATSURESI_SAAT -->EN UZUN TESLÝMAT SÜRESÝ
FROM ORDERS O
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
--INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID 
-------------------------------------------------------------------------------

