SELECT * FROM CUSTOMERS WHERE BIRTHDATE BETWEEN '19900101' AND '20000101'

UPDATE CUSTOMERS SET AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE()) WHERE CUSTOMERNAME LIKE '%Volkan%'

UPDATE CUSTOMERS SET AGE='' WHERE CUSTOMERNAME='Volkan ÇEKIP'