-------------------------------STORED PROCEDURE-----------------------------
 
 -->STANDART SQL SORGULARIYLA YAPILAN ÝÞLEMLERE 'AD HOC QUERY' DENÝR!!
 --AD HOC QUERY ADIMLARI;
 --1.QUERY
 --2.PARSE
 --3.OPTIMIZE
 --4.COMPILE
 --5.EXECUTE
 --6.RESULT

--TURNÝKE ÖRNEÐÝ

INSERT INTO WORKERS (WORKERCODE, WORKERNAME, GENDER, BIRTHDATE, TCNO, WORKERBARCODE)
VALUES ('12345678901','ALÝ TÜRKMEN','E','19960317','12345678912',NEWID()) -->UNIQUE IDENTIFIER NEW ID DÝYEREK OLUÞTURULUR!!

SELECT * FROM WORKERS

INSERT INTO WORKERTRANSACTIONS ( WORKERID, DATE_, IOTYPE, GATEID) VALUES ('1','20200412 17:32:21','C',6)

SELECT * FROM WORKERTRANSACTIONS

TRUNCATE TABLE WORKERTRANSACTIONS

--STORE PROCEDURE NASIL YAZILIR?

--> OKUTULAN KART DOÐRU MU?

SELECT *FROM WORKERS WHERE WORKERBARCODE='E40F8630-EE5F-49DD-B5DB-08D294600201'

ALTER PROCEDURE SP_CARD_CONTROL
@WORKERBARCODE AS VARCHAR(50)
AS
BEGIN

	DECLARE @WORKERNAME AS VARCHAR(100)
	SELECT @WORKERNAME=WORKERNAME FROM WORKERS WHERE WORKERBARCODE=@WORKERBARCODE
	IF @WORKERNAME IS NULL
	BEGIN
		RAISERROR ('KART GEÇERSÝZ',16,1)
		RETURN
	END
	ELSE
	BEGIN
		SELECT @WORKERNAME
	END
END

--RAISERROR('KART GEÇERSÝZ',16,1) -->KULLANICIYA HATA BASMA KOMUTUDUR! ÝÇERÝSÝNE HATA MESAJI ALIR! 16 YA 1 SABÝTTÝR DEÐÝÞMEZ!
