
-------------------------------------------------TRIGGER--------------------------------------------------------
DECLARE @ITEMID AS INT	-->BU SCRIPT HER ÇALIÞTIÐINDA ÝÇERÝ 1 KAYIT ATIYOR!
DECLARE @DATE AS DATETIME
DECLARE @AMOUNT AS INT
DECLARE @IOTYPE AS SMALLINT

SET @ITEMID=ROUND(RAND()*4,0) -->1 ÝLE 4 ARASINDAKÝ ITEMID LERDEN RANDOM SEÇÝYORUM!
IF @ITEMID=0
	SET @ITEMID=1

SET @DATE= DATEADD(DAY,-ROUND(RAND()*365,0),GETDATE()) -->ÞU ANKÝ TARÝH ÝLE 0 ÝLE 365 ARASINDA BÝR DEÐER SEÇÝP BUNU ÇIKARTTIRIYORUM (RANDOM TARÝH ÜRETÝMÝ)

SET @AMOUNT=ROUND(RAND()*9,0)+1 -->1 ÝLE 10 ARASINDA RANDOM DEÐER ALMASINI SAÐLADIM!

SET @IOTYPE=ROUND(RAND()*1,0)+1 -->1 ÝLE 2 ARASINDA DEÐER ALIR!

SELECT
@ITEMID AS ITEMID, @DATE AS DATE_,
@AMOUNT AS AMOUNT, @IOTYPE AS IOTYPE

INSERT INTO ITEMTRANSACTIONS
(ITEMID, DATE_, AMOUNT, IOTYPE)
VALUES (@ITEMID,@DATE,@AMOUNT,@IOTYPE)

----------------------------------------------------------------------------------------------------------------

SELECT * FROM ITEMTRANSACTIONS

----------------------------------------------------------------------------------------------------------------

DECLARE @ITEMID AS INT	-->BU SCRIPT HER ÇALIÞTIÐINDA ÝÇERÝ 1000 KAYIT ATIYOR!(DÖNGÜ SAYESÝNDE)
DECLARE @DATE AS DATETIME
DECLARE @AMOUNT AS INT
DECLARE @IOTYPE AS SMALLINT
DECLARE @I AS INT=0
WHILE @I<10000
BEGIN
	SET @ITEMID=ROUND(RAND()*4,0) -->1 ÝLE 4 ARASINDAKÝ ITEMID LERDEN RANDOM SEÇÝYORUM!
	IF @ITEMID=0
	SET @ITEMID=1

	SET @DATE= DATEADD(DAY,-ROUND(RAND()*365,0),GETDATE()) -->ÞU ANKÝ TARÝH ÝLE 0 ÝLE 365 ARASINDA BÝR DEÐER SEÇÝP BUNU ÇIKARTTIRIYORUM (RANDOM TARÝH ÜRETÝMÝ)

	SET @AMOUNT=ROUND(RAND()*9,0)+1 -->1 ÝLE 10 ARASINDA RANDOM DEÐER ALMASINI SAÐLADIM!

	SET @IOTYPE=ROUND(RAND()*1,0)+1 -->1 ÝLE 2 ARASINDA DEÐER ALIR!

	SELECT
	@ITEMID AS ITEMID, @DATE AS DATE_,
	@AMOUNT AS AMOUNT, @IOTYPE AS IOTYPE

	INSERT INTO ITEMTRANSACTIONS
	(ITEMID, DATE_, AMOUNT, IOTYPE)
	VALUES (@ITEMID,@DATE,@AMOUNT,@IOTYPE)

	SET @I=@I+1
END

----------------------------------------------------------------------------------------------------------------

SELECT * FROM ITEMTRANSACTIONS

----------------------------------------------------------------------------------------------------------------
