----------------------------------------DDL-------------------------------------------

USE TEST -->TEST DATABASE INI SEÇER!(YA DA EXECUTE UN YANINDAN SEÇ)
CREATE DATABASE TEST --> TEST DATABASE I OLUÞTURDUM!
CREATE TABLE ISIMLER(ID INT IDENTITY(1,1),ISIM VARCHAR(20))
INSERT INTO ISIMLER (ISIM) VALUES ('ALÝ')
--DROP DATABASE TEST --> TEST DATABASE INI SÝLER!
SELECT * FROM ISIMLER
DROP TABLE ISIMLER
ALTER TABLE ISIMLER ADD TELEFON VARCHAR(12) -->TELEFON KOLONU EKLEDÝM ISIMLER TABLOSUNA!
ALTER TABLE ISIMLER ADD ADRES VARCHAR(500) -->ADRESS KOLUNU EKLEDIM
ALTER TABLE ISIMLER DROP COLUMN ADRES -->ADRES KOLONUNU SILDIM! 
ALTER TABLE ISIMLER ALTER COLUMN ISIM VARCHAR(50) -->VARCHAR(20)YI VARCHAR(50) YAPTIM!

-----------------------------------DEÐÝÞKEN KULLANIMI----------------------------------

DECLARE @ISIM AS VARCHAR(100) -->DEÐÝÞKEN TANIMI
SET @ISIM='ALÝ' --> ISIM DEÐÝÞKENÝNE ALÝ 'YÝ ATADIM!
SELECT @ISIM -->DEÐER ATAMADIÐIM ÝÇÝN NULL GELÝR!

DECLARE @SAYI AS INTEGER
SET @SAYI=15
DECLARE @SAYI2 AS INTEGER
SET @SAYI2=20
SELECT @SAYI AS SAYI1,@SAYI2 AS SAYI2,@SAYI+@SAYI2 AS TOPLAM -->DEÐÝÞKENLER ARASI MATEMATÝKSEL ÝÞLEM YAPILABÝLÝR!

DECLARE -->YUKARIDAKÝ KOD BLOGUYLA AYNI ÝÞÝ YAPAR!
@SAYI1 AS INTEGER,
@SAYI2 AS INTEGER,
@TOPLAM AS INTEGER

SET @SAYI1=15
SET @SAYI2=32
SET @TOPLAM=@SAYI1+@SAYI2
SELECT @SAYI1 AS SAYI1,@SAYI2 AS SAYI2,@TOPLAM AS TOPLAM
--------------------------------------------------------------------------------------
DECLARE @ISIM AS VARCHAR(100)
DECLARE @TELEFON AS VARCHAR(100)

SELECT @ISIM=ISIM , @TELEFON=TELEFON FROM ISIMLER WHERE ID=1 -->TABLODAKÝ DEÐERLERÝ DEÐÝÞKENE ATADIM!
SELECT @ISIM,@TELEFON -->TABLODAN DÖNEN DEÐERÝN TEK SATIR OLMASINA DÝKKAT ET!
--------------------------------------------------------------------------------------
DECLARE @TARIH AS DATETIME
SET @TARIH=GETDATE()

SELECT @TARIH

-------------------------------STRING FONKSIYONLAR------------------------------------

--SUBSTRING(EXPRESIION,START,LENGTH)

DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='MERHABA DUNYA'
SELECT SUBSTRING(@KELIME,9,5)

--LOWER,UPPER -->STRING IFADEYI TAMAMEN KÜÇÜK YA DA BUYUK HARFE CEVÝRÝRLER!

DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='MERHABA DUNYA'
SELECT LOWER(@KELIME)

DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='merhaba dunya'
SELECT UPPER(@KELIME)

--STRING BIRLESTIRME

DECLARE @AD AS VARCHAR(100)
SET @AD='ALÝ'
DECLARE @SOYAD AS VARCHAR(100)
SET @SOYAD='TÜRKMEN'
SELECT @AD+' '+@SOYAD

--RIGHT,LEFT -->SAÐDAN VE SOLDAN ALMAK ÝSTEDÝÐÝM HARF SAYI KADAR KELIME KISMI GETÝRÝR!

DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='MERHABA DUNYA'
SELECT LEFT(@KELIME,7)

DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='MERHABA DUNYA'
SELECT RIGHT(@KELIME,5)

--LTRIM,RTRIM,TRIM -->BOÞLUK TEMÝZLEMEYE YARAR!

DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='  MERHABA TELEVOLE    NASILSIN '
SELECT LTRIM(@KELIME) --> KELÝMELERÝN SOLUNDA YER ALAN BOÞLUKLARI(EN BAÞTAKÝ BOÞLUKLARI) SÝLER! (ORTADAKÝLERÝ SÝLMEZ DÝKKAT!)

DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='  MERHABA TELEVOLE    NASILSIN '
SELECT RTRIM(@KELIME) --> EN SONDAKÝ BOLUKLARI SÝLER!

DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='  MERHABA TELEVOLE    NASILSIN '
SELECT TRIM(@KELIME) -->HEM BAÞINI HEM SONUNU TEMÝZLER!

DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='  MERHABA TELEVOLE    NASILSIN '
SELECT LTRIM(RTRIM(@KELIME)) -->TRIM ÝLE AYNI ÇALIÞIR!

--REPLACE -->BAZI KARAKTERLERÝ BAÞKA KARAKTERLERLE DEÐÝÞTÝRMEYE YARAR!

DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='MERHABA DUNYA'
SELECT REPLACE(@KELIME,'A','E') --> MERHABA DUNYA ÝÇÝNDEKÝ A LARI E YE ÇEVÝRDÝM!
SELECT REPLACE(@KELIME,'MERHABA','HELLO') --> HELLO DUNYA YAZAR!

--LEN -->STRING IFADENIN UZUNLUÐUNU GETIRIR!

DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='MERHABA DUNYA'
SELECT LEN(@KELIME)

--STRING SPLIT -->BELÝRLÝ BÝR AYIRACA GÖRE STRINGI PARÇALAYIP BIZE TABLO OLARAK DONDURUR!

DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='MERHABA DUNYA'
SELECT * FROM string_split(@KELIME,' ') --> TABLO OLARAK DÖNDÜRECEÐÝNDEN SELECT * FROM DEDÝK! BURADA BOÞLUÐA GÖRE AYIRIP TABLO YAPTIRDIM!

DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='BTK AKADEMÝ BÜNYESÝNDE DÜZENLENEN SQL SERVER EÐÝTÝMÝNÝ BEÐENDÝÐÝNÝZÝ ÜMÝT EDÝYORUZ.'
SELECT * FROM string_split(@KELIME,' ')

-------------------------------DATETIME FONKSIYONLARI------------------------------------

--DATEADD(DATEPART,NUMBER,DATE)

DECLARE @TARIH AS DATETIME
SET @TARIH='2022-03-18 23:45:01'
DECLARE @TARIH2 AS DATETIME
SET @TARIH2=DATEADD(MONTH,6,@TARIH) -->TARIH DEÐÝÞKENÝNE 6 AY EKLEDÝM!
SELECT @TARIH,@TARIH2

DECLARE @TARIH AS DATETIME
SET @TARIH='2022-03-18 23:45:01'
DECLARE @TARIH2 AS DATETIME
SET @TARIH2=DATEADD(YEAR,6,@TARIH) -->TARIH DEÐÝÞKENÝNE 6 AY EKLEDÝM!
SELECT @TARIH,@TARIH2

DECLARE @TARIH AS DATETIME
SET @TARIH='2022-03-18 23:45:01'
DECLARE @TARIH2 AS DATETIME
SET @TARIH2=DATEADD(HOUR,6,@TARIH) -->TARIH DEÐÝÞKENÝNE 6 SAAT EKLEDÝM!
SELECT @TARIH,@TARIH2

--DATEDIFF(DATEPART,STARTDATE,ENDDATE) -->ÝKÝ TARÝH ARASI FARKI ALIR!

DECLARE @TARIH AS DATETIME
SET @TARIH='2022-03-18 23:45:01'
DECLARE @TARIH2 AS DATETIME
SET @TARIH2='2021-09-29 23:49:57'
SELECT DATEDIFF(MONTH,@TARIH2,@TARIH) --> ÝKÝ TARÝHÝN AYLARININ ARASINDAKÝ FARKI ALDIM!

--DATEFROMPARTS(YEAR,MONTH,DAY) --> YIL AY GÜN PARAMETRELERÝNDEN DEÐÝÞKEN ÜRETMEK ÝÇÝN KULLANILIR!

SELECT DATEFROMPARTS(2020,8,21) --> 2020-08-21

--DATEPART --> BÝR TARÝHÝN ÝSTENEN KISMINI GETÝRÝR!

DECLARE @TARIH AS DATETIME
SET @TARIH='2022-03-18 23:45:01'
SELECT DATEPART(MONTH,@TARIH) --> 3 Ü GETÝRÝR!

DECLARE @TARIH AS DATETIME
SET @TARIH='2022-03-18 23:45:01'
SELECT DATEPART(DW,@TARIH) --> 3 Ü GETÝRÝR!
--DW=DAYOFWEEK HAFTANIN KAÇINCI GÜNÜ? DEFAULT DEÐER ÝNGÝLÝZCE OLDUÐU ÝÇÝN HAFTANIN ÝLK GÜNÜNÜ PAZAR ALIR!!!!!!!!! 3.GÜN SALI OLUR!(BÝZDE ÇARÞAMBA GÜNÜ)

--GETDATE() --> SERVER'IN TARIH SAAT BÝLGÝSÝNÝ GETÝRÝR!

SELECT GETDATE()

------------------------------------------------------------------------------------------
-- DOÐUM TARÝHÝ GÝRÝLEN KÝÞÝNÝN YAÞINI GETÝRME--

DECLARE @TARIH AS DATE
SET @TARIH='1996-03-17'
SELECT DATEDIFF(YEAR,@TARIH,GETDATE())

-----------------------------------T-SQL'DE DÖNGÜLER--------------------------------------

--TSQL DE FOR DÖNGÜSÜ YOKTUR, WHÝLE DONDUSU VARDIR!

DECLARE @I AS INT=0 --> I 0 DAN BAÞLADI 10 DAN KÜÇÜK OLANA KADAR BU ÝÞLEMÝ GERÇEKLEÞTÝRMESÝNÝ ÝSTÝYORUM!
WHILE @I<10
BEGIN
	INSERT INTO TARIHLER (TARIH) VALUES (GETDATE())
	WAITFOR DELAY '00:00:01' -->1 SANIYE BEKLEYEREK ÝÇERÝ AT DEDÝM!
	--SELECT @I --ALTERNATÝFÝ --PRINT @I
SET @I=@I+1
END

SELECT * FROM TARIHLER 

------------------------------------------------------------------------------------------

--RASTGELELÝK OLUÞTURMAK ÝÇÝN DÖNGÜ KULLANMALISIN!

SELECT ROUND(RAND()*611,0) --> RAND 0 ÝLE 1 ARASINDA RANDOM SAYI ÜRETÝR! -->BUNU DÖNGÜNÜN ÝÇÝNE YAZ!!!!!!!!
--> BUNU 611 ÝLE ÇARPARSAM 0 ÝLE 611 ARASINDA RANDOM SAYI ÜRETÝR!
--> ROUND ÝLE DE YUVARLAMA ÝÞLEMÝ YAPIP SONUNA ,0 YAZARSAM VÝRGÜLDEN SONRA 0 BASAMAK GELECEÐÝNÝ SÖYLEMÝÞ OLURUM!

SET @DOGUMTARIHI = DATEADD(DAY,ROUND(RAND()*18250,0),'1950-01-01') --> 18250 GÜNDEN(50 YIL) RANDOM SEÇ, TAM SAYIYA YUVARLA VE 1950-01-01 TARIHINI ÜZERÝNE O SAYIYI EKLEYÝP BANA BÝR TARIH OLARAK GETIR!









