----------------------------------VIEW--------------------------------------

-->GERÇEKTE BÝR TABLO OLMAYAN AMA TABLO GÝBÝ ÇALIÞMASINI ÝSTEDÝÐÝMÝZ YAPILARDIR!
-->CREATE ÝLE OLUÞTURULUR, DROP ÝLE SÝLÝNÝR, ALTER ÝLE DEÐÝÞTÝRÝLÝR!
--> VIEW ICERISINDE ORDER BY KULLANILAMAZ!!

CREATE VIEW VWORDERS -->VIEW OLUÞTUR SCRIPTE ÝSÝM VER AS DEN SONRA ÝSTEDÝÐÝN ÖZELLÝKLERÝ YAZ!
AS
--SELECT COUNT(*) FROM ORDERDETAILS
--SELECT COUNT(*) FROM INVOICES
SELECT
U.USERNAME_ KULLANICIADI, U.NAMESURNAME ADSOYAD,
C.COUNTRY ÜLKE,CT.CITY ÞEHÝR,T.TOWN ILCE,A.ADDRESSTEXT ACIKADRES,
O.ID SIPARISID,O.DATE_ SIPARISTAIH,ITM.ITEMCODE URUNKODU,
ITM.ITEMNAME URUNADI,ITM.BRAND MARKA,OD.AMOUNT MIKTAR,
OD.UNITPRICE BIRIMFIYAT,OD.LINETOTAL SATIRTOPLAMI
FROM
ORDERDETAILS AS OD
INNER JOIN ORDERS AS O ON OD.ORDERID=O.ID
INNER JOIN ITEMS AS ITM ON ITM.ID=OD.ITEMID
INNER JOIN USERS AS U ON U.ID=O.USERID
INNER JOIN ADDRESS AS A ON A.ID=O.ADDRESSID
INNER JOIN COUNTRIES AS C ON C.ID=A.COUNTRYID
INNER JOIN CITIES AS CT ON CT.ID=A.CITYID
INNER JOIN TOWNS AS T ON T.ID=A.TOWNID
INNER JOIN PAYMENTS AS P ON P.ORDERID=O.ID

-----------------------------------------------------------------------------

CREATE VIEW VWORDERS2 -->VIEW OLUÞTUR SCRIPTE ÝSÝM VER AS DEN SONRA ÝSTEDÝÐÝN ÖZELLÝKLERÝ YAZ!
AS
--SELECT COUNT(*) FROM ORDERDETAILS
--SELECT COUNT(*) FROM INVOICES
SELECT
U.USERNAME_ KULLANICIADI, U.NAMESURNAME ADSOYAD,
C.COUNTRY ÜLKE,CT.CITY ÞEHÝR,T.TOWN ILCE,A.ADDRESSTEXT ACIKADRES,
O.ID SIPARISID,O.DATE_ SIPARISTAIH,ITM.ITEMCODE URUNKODU,
ITM.ITEMNAME URUNADI,ITM.BRAND MARKA,OD.AMOUNT MIKTAR,
OD.UNITPRICE BIRIMFIYAT,OD.LINETOTAL SATIRTOPLAMI
FROM
ORDERDETAILS AS OD
INNER JOIN ORDERS AS O ON OD.ORDERID=O.ID
INNER JOIN ITEMS AS ITM ON ITM.ID=OD.ITEMID
INNER JOIN USERS AS U ON U.ID=O.USERID
INNER JOIN ADDRESS AS A ON A.ID=O.ADDRESSID
INNER JOIN COUNTRIES AS C ON C.ID=A.COUNTRYID
INNER JOIN CITIES AS CT ON CT.ID=A.CITYID
INNER JOIN TOWNS AS T ON T.ID=A.TOWNID
INNER JOIN PAYMENTS AS P ON P.ORDERID=O.ID

WHERE U.USERNAME_='Z_DALAMANLI'

SELECT * FROM VWORDERS --> VIEW LADIÐIM VERÝ ARTIK BÝR TABLO GÝBÝ ÇALIÞIYOR!!!!
SELECT * FROM VWORDERS2 WHERE ÞEHÝR='ANKARA'

--------------------------------------------------------------------------------
CREATE VIEW VW_AYLARA_GORE_SATISLAR
AS

SELECT
DATEPART(YEAR,O.DATE_) AS YIL,DATEPART(MONTH,O.DATE_) AS AY,
--CASE
	--WHEN DATEPART(MONTH,O.DATE_)=1 THEN 'OCAK'
	--WHEN DATEPART(MONTH,O.DATE_)=2 THEN 'ÞUBAT'
	--WHEN DATEPART(MONTH,O.DATE_)=3 THEN 'MART'
	--WHEN DATEPART(MONTH,O.DATE_)=4 THEN 'NÝSAN'
	--WHEN DATEPART(MONTH,O.DATE_)=5 THEN 'MAYIS'
	--WHEN DATEPART(MONTH,O.DATE_)=6 THEN 'HAZÝRAN'
	--WHEN DATEPART(MONTH,O.DATE_)=7 THEN 'TEMMUZ'
	--WHEN DATEPART(MONTH,O.DATE_)=8 THEN 'AÐUSTOS'
	--WHEN DATEPART(MONTH,O.DATE_)=9 THEN 'EYLÜL'
	--WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'EKÝM'
	--WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'KASIM'
	--WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'ARALIK'
--END AS AY,
SUM(AMOUNT) AS TOPLAMMIKTAR, SUM(LINETOTAL) AS SATIRTOPLAMI,
COUNT(OD.ID) AS URUNSAYISI,COUNT(DISTINCT O.ID) AS MUSTERÝSAYISI
FROM
ORDERDETAILS AS OD
INNER JOIN ORDERS AS O ON OD.ORDERID=O.ID
INNER JOIN ITEMS AS ITM ON ITM.ID=OD.ITEMID
INNER JOIN USERS AS U ON U.ID=O.USERID
INNER JOIN ADDRESS AS A ON A.ID=O.ADDRESSID
INNER JOIN COUNTRIES AS C ON C.ID=A.COUNTRYID
INNER JOIN CITIES AS CT ON CT.ID=A.CITYID
INNER JOIN TOWNS AS T ON T.ID=A.TOWNID
INNER JOIN PAYMENTS AS P ON P.ORDERID=O.ID

GROUP BY DATEPART(YEAR,O.DATE_),DATEPART(MONTH,O.DATE_)

SELECT * FROM VW_AYLARA_GORE_SATISLAR
ORDER BY YIL,AY

--------------------------------------------------------------------------------
ALTER VIEW VW_SIPARIS_DETAYI
AS
SELECT 
U.USERNAME_ KULLANICIADI, U.NAMESURNAME ADSOYAD, U.TELNR1 AS TEL1,
U.TELNR2 AS TEL2,ITM.CATEGORY1 AS KATEGORI1,ITM.CATEGORY2 AS KATEGORI2,
ITM.CATEGORY3 AS KATEGORI3, ITM.CATEGORY4 AS KATEGORI4,
C.COUNTRY ÜLKE,CT.CITY ÞEHÝR,T.TOWN ILCE,A.ADDRESSTEXT ACIKADRES,
O.ID SIPARISID,O.DATE_ SIPARISTAIH,ITM.ITEMCODE URUNKODU,
ITM.ITEMNAME URUNADI,ITM.BRAND MARKA,OD.AMOUNT MIKTAR,
OD.UNITPRICE BIRIMFIYAT,OD.LINETOTAL SATIRTOPLAMI,
CONVERT(DATE,O.DATE_) AS SIPARISTARIHI,CONVERT(TIME,O.DATE_) AS SIPARISZAMANI,
DATEPART(YEAR,O.DATE_) AS YIL,
CASE
	WHEN DATEPART(MONTH,O.DATE_)=1 THEN '01.OCAK'
	WHEN DATEPART(MONTH,O.DATE_)=2 THEN '02.ÞUBAT'
	WHEN DATEPART(MONTH,O.DATE_)=3 THEN '03.MART'
	WHEN DATEPART(MONTH,O.DATE_)=4 THEN '04.NÝSAN'
	WHEN DATEPART(MONTH,O.DATE_)=5 THEN '05.MAYIS'
	WHEN DATEPART(MONTH,O.DATE_)=6 THEN '06.HAZÝRAN'
	WHEN DATEPART(MONTH,O.DATE_)=7 THEN '07.TEMMUZ'
	WHEN DATEPART(MONTH,O.DATE_)=8 THEN '08.AÐUSTOS'
	WHEN DATEPART(MONTH,O.DATE_)=9 THEN '09.EYLÜL'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN '10.EKÝM'
	WHEN DATEPART(MONTH,O.DATE_)=11 THEN '11.KASIM'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN '12.ARALIK'
END AS AY,
CASE
	WHEN DATEPART(DW,O.DATE_)=2 THEN '1.PZT' --> DEFAULT ÝNGÝLÝZCE OLDUÐU ÝÇÝN HAFTANIN GÜNLERÝ PAZARDAN BAÞLIYOR, TÜRKÇE YE UYARLADIM!!
	WHEN DATEPART(DW,O.DATE_)=3 THEN '2.SAL'
	WHEN DATEPART(DW,O.DATE_)=4 THEN '3.CAR'
	WHEN DATEPART(DW,O.DATE_)=5 THEN '4.PER'
	WHEN DATEPART(DW,O.DATE_)=6 THEN '5.CUM'
	WHEN DATEPART(DW,O.DATE_)=7 THEN '6.CMT'
	WHEN DATEPART(DW,O.DATE_)=1 THEN '7.PAZ'

END AS HAFTANINGUNU

FROM

ORDERDETAILS AS OD
INNER JOIN ORDERS AS O ON OD.ORDERID=O.ID
INNER JOIN ITEMS AS ITM ON ITM.ID=OD.ITEMID
INNER JOIN USERS AS U ON U.ID=O.USERID
INNER JOIN ADDRESS AS A ON A.ID=O.ADDRESSID
INNER JOIN COUNTRIES AS C ON C.ID=A.COUNTRYID
INNER JOIN CITIES AS CT ON CT.ID=A.CITYID
INNER JOIN TOWNS AS T ON T.ID=A.TOWNID
INNER JOIN PAYMENTS AS P ON P.ORDERID=O.ID
